name: Release binaries

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build and release binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Execute CGO builds using XGO
        uses: crazy-max/ghaction-xgo@v1
        # docs: https://github.com/marketplace/actions/golang-cgo-cross-compiler#inputs
        with:
          xgo_version: latest
          go_version: 1.17
          dest: build
          pkg: cmd
          prefix: server
          targets: windows/amd64,linux/386,linux/amd64,darwin/386,darwin/amd64
          # Prints the build commands as compilation progresses (default false)
          x: true
          ldflags: -w -s
          buildmode: c-shared
          working_dir: ./src-go/server
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build standalone jar file
        run: ./gradlew fatJar
      # TODO: also build cross platform fatjar, containing all C binaries as 'resources'
      - name: Upload go binaries
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "./src-go/server/build/*;./build/libs/*.jar"
          delete_file: "./src-go/server/build/*.h"
          tags: true
          draft: true